name: CPP Azure Redis Instance
trigger: none
pr:
- main

resources:
  repositories:
  - repository: cppAzureDevOpsTemplates
    type: github
    name: hmcts/cpp-azure-devops-templates
    ref: 'main'
    endpoint: 'hmcts'

extends:
  template: pipelines/terratest.yaml@cppAzureDevOpsTemplates
  parameters:
    agentPool: "ubuntu-ado-agents-mdv"
    azureServiceConnection: "ado_nonlive_workload_identity"
    terratestTimeout: "30"
    tfversion: 1.14.3
